### ISSUE TITLE
Syncing profiles

### ISSUE THREAD

**Issue by c-shankar** [KatsuteDev/Settings-Repository#224]
### Feature

Would be great if this extension supports syncing user profiles

### Reason

Vscode stores profiles in the %APPDATA%\Code\User\profiles directory. extension and settings that are part of profiles should be synced.

**Comment by Katsute** [comment]
Testing has revealed that this feature is not possible to implement, VSCode keeps overwriting any changes to the profile list so this extension would be unable to load any new profiles.

For this sync you will need to use the native sync that VSCode offers.
